### ISSUE TITLE
can i get the pose?

### ISSUE THREAD

**Issue by smart4654154** [cvlab-kaist/PF3plat#1]
you let the network predict the camera poses for all input images while also learning the varying scale factors across different scenes.

so  can I get the predicted pose result?
thank you.

论文中写道您可以让网络预测所有输入图像的相机姿态，同时学习不同场景中的不同比例因子。
那么我能得到预测的姿势结果吗？
非常感谢。

**Comment by smart4654154** [comment]
What I mean is, where can the predicted pose be located and output it?
I want to generate results similar to colmap matching, such as bin or blender JSON files
我的意思是预测的pose在代码的哪个位置，可以输出吗？
我想生成类似colmap匹配的结果，是bin，或者blender的json文件

**Comment by SunghwanHong** [comment]
Hi, 

If you check here: https://github.com/cvlab-kaist/PF3plat/blob/eca99cb057f4397f174b4685d9f4947e5d061ff6/src/model/encoder/encoder_costvolume.py#L574C27-L574C46, refine_sync_abspose should have the poses for all the input images.
