### ISSUE TITLE
Question about test-time optimization (TTO) strategy in Table 5

### ISSUE THREAD

**Issue by fangzhou2000** [cvlab-kaist/PF3plat#3]
Excellent work!

I have two questions about the test-time optimization (TTO) strategy mentioned in the paper:

1. How is the test-time optimization strategy implemented in code (Tab 5a "Ours + TTO")? Is it simply replacing the estimated pose with the ground truth pose? I would appreciate it if you could share the corresponding code.

2. In Table 1, do you adopt a similar TTO strategy for the proposed method? If not, will adopting TTO in Table 1 further improve the evaluation metrics?

**Comment by SunghwanHong** [comment]
Hi, 

Sorry for the late reply.

1. Ours + TTO is done simply by combining our codebase with Instantsplat. We do not replace the pose with the ground-truth pose. We simply follow the instantsplat TTO strategy. We can share the code if you want. Please email to me! 
2. The results are without TTO. Our default setting is a single feed-forward setting, where TTO is not included. Only the Ours + TTO includes TTO process.

**Comment by fangzhou2000** [comment]
Thank you for the detailed reply!
